spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/UserCenter?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
#    redis 配置
#  redis:
#    port: 6379
#    host: localhost
#    database: 1
#    password: 123456
  session:
    # 86400分钟 两个月
    timeout: 86400
#    store-type: redis

server:
  port: 8080
  servlet:
    context-path: /api
  reactive:
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 配置 MyBatis SQL 执行日志输出级别
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
